---
title: "GMBP bitcoin-Sharpe Ratio"
author: "Andrew and Rick"
date: "2018年2月1日"
output: html_document
---

```{r}
p=read.csv('C:\\GMBPbitcoin\\1.csv')
b=read.csv('C:\\GMBPbitcoin\\2.csv')
```
```{r}
date=as.character(p[,2])
bit=data.frame()
j=1
for (i in 1:length(b[,2])){
  if (as.character(b[i,2]) %in% date){
    bit[j,1]=as.character(b[j,2])
    bit[j,2]=as.numeric(b[j,3])
    j=j+1
  }
  }

```
```{r}
port=data.frame(p)
```

```{r}
portf=data.frame()
bit[1,3]=0
bit[c(2:802),3]=diff(log(bit[,2]))
portf[1,1]=0
portf[c(2:802),1]=diff(log(port[,3]))
```
```{r}
ret=data.frame()
for (i in 1:802){
ret[i,1]=as.character(p[i,2])
}
ret[,2]=portf[,1]
ret[,3]=bit[,3]
```

```{r}
Sharpe_calc <- function(start, end, b,r_f ){
  w=1-b
  dlylogr=c()
dlyret=w*((exp(ret[c(start:end),2])-1))+(1-w)*(exp(ret[c(start:end),3])-1)
r_p=252*mean(dlyret)
sigma_p=sd(dlyret)*(252)^0.5
Sharpe=(r_p-r_f)/sigma_p
return(Sharpe)
}
wlist=c(seq(0,0.2,0.01))
rest=matrix(nrow = 21,ncol=781)
for (z in 1:21){
  for (j in 1:781){
result=Sharpe_calc(j,802,wlist[z],0.035)
rest[z,j]=result
}}
```
```{r}
#install.packages("plotly")
library(plotly)
```

```{r}
Sharpe_ratio=rest
plot_ly(z = ~Sharpe_ratio) %>% add_surface()
```